- apps/api/src/weapons/weapons.service.spec.ts
- apps/web/package.json
- apps/web/src/pages/weapons/_/components/create-weapon.tsx
- apps/web/src/pages/weapons/_/components/update-weapon.tsx
- package.json
- packages/database/prisma/migrations/20231016011246_dev/migration.sql
- packages/database/prisma/schema.prisma
- packages/schema/src/user/user.schema.ts
- packages/schema/src/weapon/weapon.schema.ts
- yarn.lock
schemaパッケージからzodスキーマを呼び出してもエラーにならないように修正
---
依存パッケージのバージョンを固定し、バグを解消した
---
prismaのスキーマが変更されているため、更新が必要
パッケージの依存関係が変わっているため、再インストールが必要
---
#12 
---
prismaのスキーマで定義したenumをなぜかエラーが出てimportできない
一旦schemaパッケージのほうで同じ定義をして対処している
> 12 feature request フロントエンドでschemaパッケージを呼び出したときに発生するエラーの解決

- .github/workflows/add-labels-on-pr.yml
#31 
---
- PRにラベルを自動付与するActionsを作成した
---
---
---
> chore(env): PRにラベルを自動付与するActionsを作成

- .github/workflows/remove-labels-on-issue-closed.yml
#35 
---
- Issueをクローズした時に`wip`というラベルを削除するActionsを作成した
---
---
---
> chore(env): Create remove-labels-on-issue-closed.yml

- .github/CODEOWNERS
#37 
---
- @waonpad を全コードのオーナーに設定した
---
リポジトリ保護のため
---
---
> chore(config): @waonpadを全コードのオーナーに設定

- .github/workflows/assgin-author-to-pr.yml
#38 
---
- 誰もアサインされなかった場合, 未設定のままだと困るので自動で設定するようにした
---
---
---
> chore(env): Create assgin-author-to-pr.yml

- packages/schema/src/user/user.schema.ts
- packages/schema/src/weapon/weapon.schema.ts
- packages/schema/turbo/generators/config.ts
- packages/schema/turbo/generators/templates/feature/feature.schema.ts.hbs
- packages/schema/turbo/generators/templates/feature/index.ts.hbs
#18 
---
- コード生成用テンプレートを作成した
- 小さいコードの間違いを見つけたためついでに修正
---
<rootDir>/packages/schemaで
```
yarn turbo gen schema
```
でスキーマを生成するスクリプトを実行
---
---
> 18 feature request schemaのコード生成用テンプレート

- README.md
#8 
---
- schemaパッケージの概要をドキュメントに追加した
---
---
---
> docs(env): schemaパッケージの概要をドキュメントに追加

- apps/api/openapi.yml
- apps/api/src/util/generate-api-response-options.util.ts
- apps/api/src/util/index.ts
- apps/api/src/weapon/weapon.controller.ts
- apps/api/src/weapon/weapon.service.spec.ts
- apps/api/src/weapon/weapon.service.ts
- apps/api/turbo/generators/templates/resource/resource.controller.ts.hbs
- apps/api/turbo/generators/templates/resource/resource.service.spec.ts.hbs
- apps/api/turbo/generators/templates/resource/resource.service.ts.hbs
- apps/web/src/pages/weapons/_/api/get-weapons-with-pages.ts
- apps/web/turbo/generators/templates/pages/features/_/api/get-features-with-pages.ts.hbs
- packages/schema/src/common/pagination/index.ts
- packages/schema/src/common/pagination/page-number-pagination-meta.schema.ts
- packages/schema/src/common/pagination/page-number-pagination-options.schema.ts
#17 
---
- apiレスポンスのcontent-typeにエラーが出ないように正しい値を設定するユーティリティ関数を作成
- スキーマの設定方法を間違えていたため、正しく設定するように修正し、設定しやすくするため上の関数とまとめた
- ページでDBからデータを取得する時に返ってくるデータと型が違っていたため型を合わせた
- 修正を既存のファイルに反映
---
---
---
> 17 bug dreddのテストが上手くいかないfail headers at content type no enum match for applicationjson charset=utf 8

- apps/api/test/dredd/create-weapon.hook.js
- apps/api/test/dredd/delete-weapon.hook.js
- apps/api/test/dredd/get-weapon.hook.js
- apps/api/test/dredd/update-weapon.hook.js
> fix(api): 🐞 テストパスの記述ミスを修正

- apps/api/openapi.yml
- apps/api/package.json
- apps/api/src/util/generate-api-response-options.util.ts
- apps/api/src/util/generate-schema.util.ts
- apps/api/src/util/index.ts
- apps/api/src/weapon/weapon.controller.ts
- apps/api/turbo/generators/templates/resource/resource.controller.ts.hbs
- packages/schema/package.json
- packages/schema/src/weapon/weapon.schema.ts
- yarn.lock
#68 
---
- Issueのタスクを全てはできていない
- openapi.ymlにdescriptionとexampleを自動で書き込むところまでやった
---
---
---
> 68 feature zodスキーマによって作成されたapiドキュメントからモックデータを生成したい

- apps/web/.prettierignore
- apps/web/src/__mocks__/server/handlers/weapon.handler.ts
- apps/web/src/__mocks__/server/index.ts
- apps/web/src/__mocks__/server/utils.ts
- apps/web/src/constants/env/createEnv.ts
- apps/web/src/lib/react-query/query-config.ts
- apps/web/src/lib/react-query/types.ts
- apps/web/src/main.tsx
- apps/web/src/types/index.ts
- apps/web/src/utils/zod.ts
- package.json
- yarn.lock
#73 
#75 
---
---
- いろいろ気づいたバグがあったので修正した
---
---
> 73 feature msw上でバリデーションを行えるようにする

- package-scripts.js
> chore(env): 🤖 セットアップ時にパッケージのビルドを実行するよう修正

- packages/prefecture/src/prefectures.ts
#89 
---
以下の隣接関係を追加した
- 広島-愛媛
- 香川-岡山
- 兵庫-徳島
---
---
---
> config(config): ⚙ 県同士の隣接関係を修正

- apps/api/src/util/compute-game-data.util.ts
- apps/web/src/pages/(todofuken)/_/components/screens/game-battle.tsx
> feat(config): ✨ 対戦引き分け時にそのままゲームを継続するようにした

- apps/api/openapi.yml
- apps/api/src/prefecture/config/prefecture-include-default.ts
- apps/api/src/prefecture/prefecture.service.ts
- apps/api/src/todofuken/game/game.service.ts
- apps/web/src/pages/(todofuken)/_/api/get-prefecture-stats.ts
- apps/web/src/pages/(todofuken)/_/components/game-battle-display.tsx
- apps/web/src/pages/(todofuken)/_/components/prefecture-overview-dialog.tsx
- apps/web/src/pages/(todofuken)/_/components/screens/game-battle.tsx
- apps/web/src/pages/(todofuken)/_/components/screens/game-lobby.tsx
- apps/web/src/pages/(todofuken)/_/components/screens/game-select-factor.tsx
- packages/database/prisma/migrations/20231031112749_/migration.sql
- packages/database/prisma/migrations/20231031120800_/migration.sql
- packages/database/prisma/schema.prisma
- packages/database/src/seed.ts
- packages/schema/src/prefecture/prefecture.schema.ts
- packages/schema/src/prefecture/stats/prefecture-stats.schema.ts
- packages/schema/src/todofuken/game/log/game-log.schema.ts
#110 
---
---
---
---
反映させるには以下のコマンドを実行
```
cd packages/databse
npx prisma migrate reset
cd ../../
nps prepare.database
cd packages/schema
yarn build
```
> 110 feature ゲームの要素吸収機能を実装する

- apps/api/src/todofuken/game/game.service.ts
- apps/web/src/pages/(todofuken)/_/components/screens/game-battle.tsx
> feat(api): ✨ ミスをしても終了しないようにした

- apps/api/openapi.yml
- apps/web/src/pages/(todofuken)/_/components/game-status.tsx
- apps/web/src/pages/(todofuken)/_/config/game.tsx
- package-scripts.js
> 113 feature ゲームのタイム計測を可能にする

- docs/SETUP.md
> docs(env): ✏ firebaseプロジェクトのセットアップ手順をまとめた

- packages/database/seed-data/prefecture-stats/_template.ts
- packages/database/seed-data/prefecture-stats/types.ts
> chore(env): 🤖 都道府県データ保存用のテンプレートと型定義を作成した

- apps/api/turbo/generators/templates/resource/resource.controller.spec.ts.hbs
- apps/api/turbo/generators/templates/resource/resource.service.spec.ts.hbs
- apps/api/turbo/generators/templates/resource/resource.service.ts.hbs
> 102 feature prismaのdiの仕方が変わったのでテンプレートに反映させる

- apps/web/src/lib/axios.ts
> fix(none): Update axios.ts

- apps/web/src/pages/(todofuken)/_/components/maps/prefecture-svg.tsx
#118 
---
---
---
---
- 適当に書いてからリファクタリングしようとしたら挙動がわからなくなって動かなくなったため、一旦やめた
- コードが汚すぎるため、余裕ができれば今度また書き直す
> feat(web): ✨ 都道府県ごとのsvgを表示するコンポーネントを作成した

- apps/web/src/lib/react-error-boundary.tsx
- apps/web/src/providers/app-provider.tsx
- apps/web/src/utils/hooks/useWindowEvent.ts
> 132 feature 非同期処理とイベントハンドラ内で発生したエラーをerrorboundaryで捕まえられるようにする

- apps/web/src/auth/use-auth.ts
- apps/web/src/pages/(todofuken)/_/hooks/use-game.ts
- apps/web/src/pages/(todofuken)/_/providers/game-provider.tsx
- apps/web/src/pages/(todofuken)/game/index.tsx
> 133 feature ログアウト時や復帰不可能なエラーが発生している場合にゲームの情報をcookieから削除する

- apps/web/src/pages/(todofuken)/_/components/maps/japan-radio-svg-map.tsx
> feat(web): ✨ マップを折り返せるようにした

- apps/web/src/components/maps/japan-radio-svg-map.tsx
#142 
---
- マップで沖縄を折り返したときにわかりやすくするための線を作成した
- propsの状態が変わったときに要素の移動がもとに戻らない状態だったので、一度全てリセットしてから再計算するようにマップコンポーネントを修正した
---
createElementだと要素は追加できているのになぜか画面に表示されなかったので、対処方法を調べて、独立したパスをsvgに挿入できるようにした
---
---
マップコンポーネントに関係する関数が多くなっているのでフックとして分けたほうがいいかも
> feat(web): ✨ マップで沖縄を折り返したときにわかりやすくするための線を作成した

- apps/web/src/components/maps/config/index.ts
- apps/web/src/components/maps/dispatch-svg-map-location-element.tsx
- apps/web/src/components/maps/hooks/use-dispatch-svg-map-location-event.ts
- apps/web/src/components/maps/japan-radio-svg-map.tsx
- apps/web/src/components/maps/map-separator.tsx
- apps/web/src/components/maps/types/index.ts
- apps/web/src/components/maps/utils/get-relocation-type.ts
- apps/web/src/components/maps/utils/relocation-by-type.ts
- apps/web/src/components/maps/utils/shift-path.ts
#148 
---
- Issueの解決
- マップコンポーネントの実装のリファクタリング
---
以下の動画のように、任意の領域で対象要素にイベントを発生させられるようにした(グレーの部分)
https://github.com/waonpad/miraisozoten/assets/76579358/102c4498-2e85-4ddd-b809-cb9ce5a268a6
---
---
> 148 feature マップ上でクリックしにくい都道府県の反応範囲を広げたい

- apps/api/openapi.yml
- apps/api/src/prisma/prisma.service.ts
- apps/web/src/pages/(todoufuken)/_/config/game.tsx
- packages/database/prisma/migrations/20231106105819_/migration.sql
- packages/database/prisma/migrations/20231110112114_/migration.sql
- packages/database/prisma/schema.prisma
- packages/schema/src/todoufuken/game/game.enum.ts
> refactor(none): 🔨 ゲームの難易度の識別名を修正した

- apps/web/src/pages/(todoufuken)/_/components/game-difficulty-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-mode-select.tsx
- apps/web/src/pages/(todoufuken)/_/config/game.tsx
- apps/web/src/utils/strict-entries.ts
> 155 feature ゲームの難易度とモードのラベルを識別名にマッピングする

- apps/api/src/todoufuken/game/game.controller.ts
- apps/api/src/todoufuken/game/game.service.ts
- apps/web/src/pages/(todoufuken)/_/api/give-up-game.ts
- apps/web/src/pages/(todoufuken)/_/components/game-header.tsx
- apps/web/src/pages/(todoufuken)/_/hooks/use-game.ts
- packages/database/prisma/schema.prisma
- packages/schema/src/todoufuken/game/game.enum.ts
> feat(web): ✨ ゲームのギブアップ処理を追加して、ステートの定数も最小限にした

- apps/web/src/auth/use-auth.ts
- apps/web/src/constants/cookie-names.ts
- apps/web/src/pages/(todoufuken)/_/components/game-header.tsx
- apps/web/src/pages/(todoufuken)/_/hooks/use-game.ts
> style(none): 👙 大文字であるべき部分が小文字になっていたのを修正

- apps/web/src/pages/index.tsx
#163 
---
---
土台を作成しただけで中身はない
---
---
> feat(web): ✨ トップページ用のコンポーネントを作成した

- apps/web/src/auth/auth-guard.tsx
- apps/web/src/components/elements/auth-icon-button/index.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-header.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-result.tsx
- apps/web/src/pages/index.tsx
- apps/web/src/pages/menu/index.tsx
- apps/web/src/router.ts
> 164 feature メニュー画面用のコンポーネントを作成する

- apps/api/openapi.yml
- apps/api/src/todoufuken/game/game.controller.ts
- apps/api/src/todoufuken/game/game.service.ts
- apps/web/src/auth/auth-guard.tsx
- apps/web/src/pages/(todoufuken)/_/api/get-infinite-games.ts
- apps/web/src/pages/archives/_/components/game-archive-list-item.tsx
- apps/web/src/pages/archives/_/components/infinite-game-archive-list.tsx
- apps/web/src/pages/archives/index.tsx
- apps/web/src/pages/menu/index.tsx
- apps/web/src/router.ts
- packages/database/prisma/migrations/20231111143857_dev/migration.sql
- packages/schema/src/todoufuken/game/game.schema.ts
#165 
#160 
---
---
- まだ土台しかできていないので後から手を加えていく必要がある
- 成績を取得できるエンドポイントは、#160 に最初に書いたものとは別のパスで実装した(/gamesに対してクエリでユーザーIDを指定して絞り込む方法にした)
---
---
> 165 feature 成績一覧画面用のコンポーネントを作成する

- apps/web/src/pages/(todoufuken)/_/api/get-infinite-games.ts
- apps/web/src/pages/ranking/_/components/game-ranking-filter.tsx
- apps/web/src/pages/ranking/_/components/game-ranking-list-header.tsx
- apps/web/src/pages/ranking/_/components/game-ranking-list-item.tsx
- apps/web/src/pages/ranking/_/components/infinite-game-ranking-list.tsx
- apps/web/src/pages/ranking/index.tsx
> 166 feature ランキング画面用のコンポーネントを作成する

- apps/api/openapi.yml
- apps/api/src/todoufuken/game/game.controller.ts
- apps/api/src/todoufuken/game/game.service.ts
- apps/web/src/pages/(todoufuken)/_/api/submit-game-turn-action.ts
- apps/web/src/pages/(todoufuken)/_/components/game-difficulty-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-header.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-mode-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-setting-submit.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-status.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-turn-factor-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-turn-question.tsx
- apps/web/src/pages/(todoufuken)/_/components/give-up-icon-button.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-lobby.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-result.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-turn-action.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-turn-result.tsx
- apps/web/src/pages/(todoufuken)/_/config/game.tsx
- apps/web/src/pages/(todoufuken)/_/hooks/use-game-settings.ts
- apps/web/src/pages/(todoufuken)/_/hooks/use-game-turn-action.ts
- apps/web/src/pages/(todoufuken)/_/hooks/use-game.ts
- apps/web/src/pages/menu/index.tsx
- apps/web/src/router.ts
- apps/web/src/utils/asset.ts
> 184 feature ゲーム部分のリファクタリング

- apps/web/src/pages/(todoufuken)/_/api/start-game.ts
- apps/web/src/pages/(todoufuken)/_/api/submit-game-turn-action.ts
- apps/web/src/pages/(todoufuken)/_/components/confirm-give-up-dialog.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-battle-display.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-difficulty-info.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-difficulty-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-header.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-mode-info.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-mode-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-setting-submit.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-status.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-turn-factor-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-turn-question.tsx
- apps/web/src/pages/(todoufuken)/_/components/prefecture-overview-dialog.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-lobby.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-result.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-turn-action.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-turn-result.tsx
- apps/web/src/pages/(todoufuken)/_/config/game.tsx
- apps/web/src/pages/(todoufuken)/_/hooks/use-game-settings.ts
- apps/web/src/pages/(todoufuken)/_/hooks/use-game-turn-action.ts
- apps/web/src/pages/(todoufuken)/_/hooks/use-game.ts
- apps/web/src/pages/(todoufuken)/_/providers/game-provider.tsx
- apps/web/src/pages/(todoufuken)/_/utils/compute-factors.ts
- apps/web/src/pages/(todoufuken)/_/utils/gat-all-factors.ts
- apps/web/src/pages/(todoufuken)/_/utils/get-turn-factor.ts
> 169 feature ゲーム部分のフロントエンドテストをしやすくするためのコメントを書く

- apps/web/src/pages/(todoufuken)/_/components/game-battle-display-with-opponent-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-turn-question.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-turn-action.tsx
- apps/web/src/pages/(todoufuken)/_/config/game.tsx
> feat(web): ✨ close #193

- apps/web/src/pages/(todoufuken)/_/components/game-battle-display-with-opponent-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-turn-action.tsx
> fix(none): 🐞 必要な情報が足りていなくてもsubmit出来てしまっていたので修正

- apps/web/package.json
- yarn.lock
> package(none): 📦 close #202

- apps/web/src/__mocks__/server/handlers/auth.handler.ts
- apps/web/src/lib/firebase.ts
- apps/web/src/test/utils/index.ts
> 192 feature フロントエンドの認証モック用コードを更新する

- apps/web/src/components/elements/auth-icon-button/index.tsx
- packages/fb-tools/lib/admin-server.js
> 199 feature ログインボタンで匿名ログインからソーシャルログインに切り替えられるようにする

- apps/api/test/dredd/dredd-config.js
- apps/api/turbo/generators/templates/test/dredd/resource/create-resource.hook.js.hbs
- apps/api/turbo/generators/templates/test/dredd/resource/delete-resource.hook.js.hbs
- apps/api/turbo/generators/templates/test/dredd/resource/get-resource.hook.js.hbs
- apps/api/turbo/generators/templates/test/dredd/resource/update-resource.hook.js.hbs
> test(api): 🧪 close #200

- apps/web/index.html
- apps/web/vite.config.ts
> feat(web): ✨ close #188

- apps/web/src/__mocks__/server/db.ts
- apps/web/src/__mocks__/server/guards/auth-guard.ts
- apps/web/src/__mocks__/server/handlers/auth.handler.ts
- apps/web/src/__mocks__/server/handlers/game.handler.ts
- apps/web/src/__mocks__/server/handlers/index.ts
- apps/web/src/__mocks__/server/handlers/prefecture-stats-metadata.handler.ts
- apps/web/src/__mocks__/server/handlers/prefecture.handler.ts
- apps/web/src/__mocks__/server/middleware/user-middleware.ts
- apps/web/src/__mocks__/server/utils/compute-game-data.ts
- apps/web/src/__mocks__/server/utils/delayed-response.ts
- apps/web/src/__mocks__/server/utils/game-relation-include.ts
- apps/web/src/__mocks__/server/utils/get-page-number-pagination-meta.ts
- apps/web/src/__mocks__/server/utils/get-request-params-object.ts
- apps/web/src/test/seeders/prefecture-stats-metadata.seeder.ts
- apps/web/src/test/seeders/prefecture-stats.seeder.ts
- apps/web/src/test/seeders/prefecture.seeder.ts
- apps/web/src/test/seeders/region.seeder.ts
#208 
---
---
---
---
リファクタリングしたい・・・
> 208 feature mswのdbにバックエンドと同じモデルとハンドラーを用意する

- .github/workflows/web.yaml
> chore(env): firebaseの接続情報をシークレットから取得、firebaseエミュレーターを起動するようにした

- apps/api/test/dredd/dredd-config.js
> refactor(none): 🔨 close #223

- packages/fb-tools/.firebaserc
- packages/fb-tools/.gitignore
> chore(env): 🤖 close #226

- apps/api/src/todoufuken/game/game.service.ts
- apps/web/src/__mocks__/server/handlers/game.handler.ts
- apps/web/src/pages/(todoufuken)/_/components/game-status.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-turn-factor-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-turn-action.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-turn-result.tsx
- apps/web/src/pages/(todoufuken)/_/utils/gat-all-factors.ts
- apps/web/src/pages/(todoufuken)/_/utils/get-turn-ally-factor.ts
- apps/web/src/pages/(todoufuken)/_/utils/get-turn-opponent-factor.ts
#231 
---
- 要素吸収を正しい形で行えるように修正した
- ゲームが絶対にクリアできないミスに気づいたので修正した
---
---
---
> feat(web): ✨ close #231

- apps/web/src/pages/(todoufuken)/_/components/game-battle-display-with-opponent-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-battle-display.tsx
- apps/web/src/pages/(todoufuken)/_/components/prefecture-overview-dialog.tsx
> style(none): 👙 close #222

- apps/web/src/pages/(todoufuken)/_/components/game-status.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-result.tsx
#237 
---
- リザルト画面に制覇数表示が不要なので削除した
---
---
---
> 237 feature ゲームの制覇数カウントは初期選択した都道府県もカウントに含めるようにする

- apps/web/package.json
- apps/web/src/vite-env.d.ts
- apps/web/vite.config.ts
- yarn.lock
#239 
---
---
このようにsvgを読み込んでスタイルの適用ができる
```js
import Icon from './icon.svg?react';
<Icon style={{ ... }} />
```
---
---
> feat(web): ✨ close #239

- apps/web/src/components/elements/image-bg-button/index.tsx
#245 
---
---
---
---
- マウスオーバー時と選択時に表示する用の画像が必要なため、用意しないといけない
> 245 feature 画像素材を背景にしたボタンを作成する

- apps/web/src/components/elements/auth-icon-button/index.tsx
- apps/web/src/pages/(todoufuken)/_/components/give-up-icon-button.tsx
- packages/ui/components/ui/button.tsx
> style(none): 👙 close #253

- apps/web/src/pages/(todoufuken)/game/index.tsx
- apps/web/src/pages/archives/index.tsx
- apps/web/src/pages/attribution/index.tsx
- apps/web/src/pages/index.tsx
- apps/web/src/pages/menu/index.tsx
- apps/web/src/pages/ranking/index.tsx
> style(web): 👙 close #187

- apps/api/src/todoufuken/game/game.controller.ts
- apps/api/src/todoufuken/game/game.service.ts
> feat(api): ✨ 自分以外のゲームの成績を取得しようとしたらエラーが返るようにした

- apps/api/openapi.yml
- apps/api/src/todoufuken/game/game.service.ts
- packages/schema/src/todoufuken/game/game.schema.ts
> feat(api): ✨ close #182

- apps/api/openapi.yml
- apps/api/src/todoufuken/game/game.service.ts
- apps/web/src/__mocks__/server/db.ts
- apps/web/src/pages/archives/_/components/infinite-game-archive-list.tsx
- apps/web/src/pages/ranking/_/components/game-ranking-list-item.tsx
- apps/web/src/pages/ranking/_/components/infinite-game-ranking-list.tsx
- apps/web/src/pages/ranking/index.tsx
- apps/web/src/utils/format.ts
- packages/database/prisma/migrations/20231123115244_/migration.sql
- packages/database/prisma/migrations/20231123135747_/migration.sql
- packages/database/prisma/schema.prisma
- packages/schema/src/todoufuken/game/game.schema.ts
> feat(api): ✨ close #179

- apps/api/src/todoufuken/game/game.service.ts
> fix(api): 🐞 close #258

- apps/web/package.json
- apps/web/src/__mocks__/server/db.ts
- apps/web/src/__mocks__/server/handlers/game.handler.ts
- apps/web/src/__mocks__/server/utils/get-request-params-object.ts
- yarn.lock
> 262 feature バックエンドのコード修正をモックサーバーに反映させる

- apps/web/src/pages/(todoufuken)/_/components/game-difficulty-info.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-mode-info.tsx
> style(web): 👙 close #171

- apps/web/src/pages/(todoufuken)/_/components/game-status.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-result.tsx
- apps/web/src/pages/(todoufuken)/_/hooks/use-game.ts
> style(web): 👙 close #259

- apps/web/src/components/maps/japan-radio-svg-map.tsx
- apps/web/src/components/maps/styles/index.css
> style(web): 👙 close #274

- apps/web/src/pages/(todoufuken)/_/components/game-battle-display-with-opponent-select.tsx
> style(web): 👙 close #277

- package-scripts.js
- packages/fb-tools/package.json
- yarn.lock
> fix(env): 🐞 close #272

- apps/web/src/components/elements/auth-icon-button/index.tsx
- apps/web/src/components/elements/confirm-logout-dialog/index.tsx
- apps/web/src/components/elements/login-alert-dialog/index.tsx
- apps/web/src/pages/menu/index.tsx
> 270 feature ログアウト時にダイアログで確認をするようにする

- apps/web/src/pages/(todoufuken)/game.explain/index.tsx
- apps/web/src/pages/menu/index.tsx
- apps/web/src/router.ts
> feat(web): ✨ close #266

- packages/database/seed-data/prefecture-stats/apple-consumption.ts
- packages/database/seed-data/prefecture-stats/baseball-population.ts
- packages/database/seed-data/prefecture-stats/bridge-count.ts
- packages/database/seed-data/prefecture-stats/convenience-store-count.ts
- packages/database/seed-data/prefecture-stats/electricity-consumption.ts
- packages/database/seed-data/prefecture-stats/forest-area.ts
- packages/database/seed-data/prefecture-stats/internet-usage-rate.ts
- packages/database/seed-data/prefecture-stats/kerosene-price.ts
- packages/database/seed-data/prefecture-stats/morning-reading-enforcement-rate.ts
- packages/database/seed-data/prefecture-stats/post-office-count.ts
- packages/database/seed-data/prefecture-stats/rice-consumption.ts
- packages/database/seed-data/prefecture-stats/starbucks-count.ts
- packages/database/seed-data/prefecture-stats/tunnel-count.ts
- packages/database/seed-data/prefecture-stats/uniqlo-count.ts
#288 
---
データの追加
---
林檎の消費量
野球人口
橋梁数
コンビニエンスストア数
電力消費量
森林面積
インターネット利用率
灯油価格
朝の読書実施率
郵便局数
ご飯消費量
スターバックス店舗数
トンネル数
ユニクロ店舗数
---
---
> feat(types): ✨ データの追加

- apps/web/src/components/elements/auth-button/index.tsx
- apps/web/src/index.css
- apps/web/src/pages/menu/index.tsx
> 307 feature メニュー画面のコーディングをする

- apps/web/src/pages/(todoufuken)/_/components/game-turn-question.tsx
> feat(web): ✨ close #305

- apps/web/src/components/transitions/fade-transition/fade-transition-provider.tsx
- apps/web/src/components/transitions/fade-transition/index.tsx
- apps/web/src/components/transitions/fade-transition/use-fade-transition.ts
- apps/web/src/pages/(todoufuken)/_/components/screens/game-lobby.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-result.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-turn-action.tsx
- apps/web/src/pages/(todoufuken)/_/components/screens/game-turn-result.tsx
- apps/web/src/pages/(todoufuken)/game.explain/index.tsx
- apps/web/src/pages/archives/index.tsx
- apps/web/src/pages/attribution/index.tsx
- apps/web/src/pages/index.tsx
- apps/web/src/pages/menu/index.tsx
- apps/web/src/pages/ranking/index.tsx
- apps/web/src/providers/app-provider.tsx
> style(web): 👙 close #289

- packages/database/src/seed.ts
#150
---
・ビルドの修正？
・シーディングするコードの作成
---
---
---
> chore(env): 🤖 close #150

- apps/web/src/components/transitions/fade-transition/fade-transition-provider.tsx
- apps/web/src/components/transitions/fade-transition/index.tsx
- apps/web/src/components/transitions/fade-transition/use-fade-transition.ts
- apps/web/src/components/transitions/fusuma-transition/fusuma-transition-provider.tsx
- apps/web/src/components/transitions/fusuma-transition/index.tsx
- apps/web/src/components/transitions/fusuma-transition/use-fusuma-transition.ts
> perf(design): ⚡️ close #316

- apps/web/src/components/foreground-animations/foreground-leaf-animation/foreground-leaf-animation.css
- apps/web/src/components/foreground-animations/foreground-leaf-animation/index.tsx
- apps/web/src/providers/app-provider.tsx
282 feature 全ての画面に動きをつける
---
背景に流れる葉っぱアニメーションの色変更
---
---
---
> 282 feature 全ての画面に動きをつける

- apps/web/vite.config.ts
> chore(config): 🤖 close #321

- apps/web/src/pages/(todoufuken)/_/components/confirm-give-up-dialog.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-battle-display-with-opponent-select.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-turn-question.tsx
- apps/web/src/pages/(todoufuken)/_/config/game.tsx
- apps/web/src/pages/(todoufuken)/game.explain/css/explain.css
- apps/web/src/pages/(todoufuken)/game.explain/index.tsx
> style(design): 👙 close #284

- apps/web/src/lib/use-sound/use-sound.ts
> feat(web): ✨ close #322

- apps/web/src/pages/attribution/_/constants/sound-attributions.ts
- apps/web/src/pages/attribution/index.tsx
> feat(web): ✨ close #343

- apps/api/Dockerfile
> chore(env): 🤖 close #62

- docs/deploy/BACK_CLOUD_RUN.md
> docs(none): ✏ 誤字修正など

- apps/web/vercel.json
> fix(web): 🐞 vercel.jsonでrewrite設定をしてみた

- apps/api/src/auth/auth.service.ts
- apps/api/src/config/environments/env.service.ts
- apps/api/src/main.ts
> fix(api): 🐞 close #354

- apps/web/vercel.json
#122 
---
- 設定が間違っていたので修正
---
---
---
> config(config): ⚙ 再修正

- apps/web/src/pages/(todoufuken)/_/config/game.tsx
#357 
---
- バグ修正
- safari, firefox, chromeでターンの結果画面のレイアウト崩れがないことを確認
---
---
---
> fix(design): 🐞 close #357

- apps/web/src/pages/(todoufuken)/_/components/game-difficulty-info.tsx
- apps/web/src/pages/(todoufuken)/_/components/game-mode-info.tsx
> fix(design): 🐞 close #361

- apps/web/src/components/layout/main/index.tsx
- apps/web/src/pages/(todoufuken)/_/components/conquered-prefectures-dialog.tsx
- apps/web/src/pages/(todoufuken)/game.explain/css/explain.css
- apps/web/src/pages/archives/_/css/archives.css
- packages/tailwind-config/tailwind.config.js
> fix(design): 🐞 close #363
